### ISSUE TITLE
Equal sign should be allowed in arguments

### ISSUE THREAD

**Issue by nfischer** [vorpaljs/bash-parser#6] opened 2016-03-26 21:09 UTC
Commands like `echo foo=bar` should be allowed, and they should be parsed as:

```javascript
> parse("echo foo=bar")
[ { type: 'command',
    command: { type: 'literal', value: 'echo' },
    args: [ [Object] ],
    redirects: [],
    env: {},
    control: ';',
    next: null } ]
> parse("echo foo=bar")[0].args
[ { type: 'literal', value: 'foo=bar' } ]
```

**Comment by parro-it** [comment] 2016-03-27 00:51
I made a PR that maybe solve the problem changing the `argument` rule in the grammar.
I'll add some comment there because I'm sure I'm doing it right.

**Comment by parro-it** [comment] 2016-07-22 12:58
Fixed in new branch. See [test](https://github.com/vorpaljs/bash-parser/blob/master/test/test-regressions.js#L30)

**Closed by parro-it** 2016-07-22 12:58 UTC
Labels: bug
